#!/usr/bin/python2.5
# -*- coding: utf-8 -*-
"""
A dirt simple IM program for your local subnet.
"""
#from __future__ import with_statement Compatibility with debian stable
from __future__ import division
import pygtk
pygtk.require('2.0')
import gtk
import gobject
gtk.gdk.threads_init()
gobject.threads_init()
import gtk.glade
import pango
import os, sys, socket, struct, threading
import traceback, datetime, re

# The IPv4 multicast group is 224.0.0.0/4
# The mcast.py demo uses 225.0.0.250, which is part of a reserved block
# The link scope is 239.255.0.0/16, the organization scope is 239.192.0.0/14
# I'm going to use the former, with the last 2 bytes being map(ord, 'SI'),
# or 239.255.83.73
SUBIM_GROUP = '239.255.83.73'
# Set this to the number of hops packets can take. 1 is fine for most homes,
# Organizations or other more complex setups may need higher numbers.
SUBIM_TTL = 3

# Change this to 8123 to test with mcast.py found in the Python demos
# 5349 = map(hex, map(ord, 'SI')), SI = SubIM, = 5349
SUBIM_PORT = 5349

# For the nick hasher
SATURATION = 1.00
LUMINANCE = 0.40

__author__ = "James Bliss <astronouth7303@gmail.com>"
__date__ = """$Date$"""
__version__ = """$Revision$"""
__credits__ = """Cuog, for helping me test.
David, for putting up with me.
Various IRC channels, for putting up with my (sometimes n00bish) questions.
PyGTK & Glade, for making this a little bit easier.
"""

_hostname = None
def getHost():
	global _hostname
	if _hostname is None:
		_hostname = unicode(socket.gethostname())
	return _hostname


def openmcastsock(group, port):
	"""
	Open a UDP socket, bind it to a port and select a multicast group
	Borrowed from the Python demos.
	"""
	#
	# Create a socket
	s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
	#
	# Allow multiple copies of this program on one machine
	# (not strictly needed)
	s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
	#
	# Bind it to the port
	s.bind(('', port))
	#
	# Look up multicast group address in name server
	# (doesn't hurt if it is already in ddd.ddd.ddd.ddd format)
	group = socket.gethostbyname(group)
	#
	# Construct binary group address
	bytes = map(int, group.split("."))
	grpaddr = 0
	for byte in bytes: grpaddr = (grpaddr << 8) | byte
	#
	# Construct struct mreq from grpaddr and ifaddr
	ifaddr = socket.INADDR_ANY
	mreq = struct.pack('ll', socket.htonl(grpaddr), socket.htonl(ifaddr))
	#
	# Add group membership
	s.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)
	#
	return s

HEADER_FORMAT = "!HL"
ARGUMENT_FORMAT = "!L"

CMD_MESSAGE = 0
CMD_USER_JOIN = 1 # Also used as the response for a user list request
CMD_USER_PART = 2
CMD_LIST_USERS = 3

class Protocol(object):
	rsock = None
	ssock = None
	
	joiners = []
	parters = []
	msgers = []
	joined = False
	
	def __init__(self):
		# Sending stuff
		self.ssock = openmcastsock(SUBIM_GROUP, SUBIM_PORT)
		ttl = struct.pack('b', SUBIM_TTL) # Time-to-live
		self.ssock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, ttl)
		# Receiving stuff
		self.rsock = openmcastsock(SUBIM_GROUP, SUBIM_PORT)
		self.joined = False
	
	def __encode(self, uni):
		return unicode(uni).encode('utf8', 'ignore') # We really shouldn't get anything
	
	def __decode(self, data):
		return unicode(data, 'utf8', 'ignore')
	
	# SENDING #
	def __send(self, cmd, *args):
		args = map(unicode, args)
		print "Protocol.__send", cmd, args
		user = unicode(getHost()).encode('utf8', 'ignore')
		data = struct.pack(HEADER_FORMAT, cmd, len(user))
		data += user
		for a in args:
			d = self.__encode(a)
			data += struct.pack(ARGUMENT_FORMAT, len(d))
			data += d
		self.ssock.sendto(data, (SUBIM_GROUP, SUBIM_PORT))
	
	def sendMessage(self, msg):
		print "Protocol.sendMessage", msg
		self.__send(CMD_MESSAGE, msg)
	
	def listUsers(self):
		print "Protocol.listUsers"
		self.userJoin(getHost())
		self.__send(CMD_LIST_USERS)
	
	def join(self):
		print "Protocol.join"
		self.__send(CMD_USER_JOIN)
		self.joined = True
	
	def part(self):
		print "Protocol.part"
		self.joined = False
		self.__send(CMD_USER_PART)
	
	# RECEIVING #
	def recieveMessage(self, user, msg):
		print "Protocol.recieveMessage", user, msg
		for c in self.msgers:
			if callable(c): c(user, msg)
	
	def userJoin(self, user):
		print "Protocol.userJoin", user
		for c in self.joiners:
			if callable(c): c(user)
	
	def userPart(self, user):
		print "Protocol.userPart", user
		for c in self.parters:
			if callable(c): c(user)
		# If it's us, send out a join message
		if user == getHost() and self.joined:
			self.join()
	
	def __reply2list(self, user):
		self.__send(CMD_USER_JOIN)
	
	COMMANDS = {
		CMD_MESSAGE : recieveMessage,
		CMD_USER_JOIN : userJoin,
		CMD_USER_PART : userPart,
		CMD_LIST_USERS : __reply2list,
	}
	
	def __readPacket(self):
		dlen = struct.calcsize(HEADER_FORMAT)
		d,src = self.rsock.recvfrom(4096)
		print "__readPacket:", repr(d),src
		cmd, ulen = struct.unpack(HEADER_FORMAT, d[:dlen])
		d = d[dlen:]
		user = self.__decode(d[:ulen])
		d = d[ulen:]
		args = []
		alen = struct.calcsize(ARGUMENT_FORMAT)
		while len(d) >= alen:
			l, = struct.unpack(ARGUMENT_FORMAT, d[:alen])
			d = d[alen:]
			args.append(self.__decode( d[:l] ))
			d = d[l:]
		if len(d):
			print "Warning: Leftover data: ", repr(d)
		return src, cmd, user, args
	
	def readOne(self):
		src, cmd, user, args = self.__readPacket()
		print "readOne:", src, cmd, user, args
		if cmd in self.COMMANDS:
			self.COMMANDS[cmd](self, user, *args)
	
	def readForever(self):
		print "Start reading"
		while True:
			try:
				self.readOne()
			except:
				traceback.print_exc()
	
	def startReading(self):
		t = threading.Thread(target=self.readForever, name="SocketReader")
		t.setDaemon(True)
		t.start()
	
	def __enter__(self):
		self.join()
	
	def __exit__(self, exc_type=None, exc_value=None, traceback=None):
		self.part()

def hsl(H,S,L):
	"""
	http://discussion.forum.nokia.com/forum/showthread.php?t=78382#post199756
	"""
	def Hue_2_RGB( v1, v2, vH ):
		if ( vH < 0 ):
			vH += 1
		if ( vH > 1 ):
			vH -= 1
		if ( ( 6 * vH ) < 1 ):
			return ( v1 + ( v2 - v1 ) * 6 * vH )
		if ( ( 2 * vH ) < 1 ):
			return v2 
		if ( ( 3 * vH ) < 2 ):
			return ( v1 + ( v2 - v1 ) * ( ( 2 / 3 ) - vH ) * 6 )
		return v1 
	H = H / 360.0
	if (S == 0 ):
		R = L
		G = L
		B = L
	else:
		if ( L < 0.5 ):
			var_2 = L * ( 1 + S )
		else:
			var_2 = ( L + S ) - ( S * L )
		var_1 = 2 * L - var_2
		R = Hue_2_RGB( var_1, var_2, H + ( 1 / 3 ) )
		G = Hue_2_RGB( var_1, var_2, H )
		B = Hue_2_RGB( var_1, var_2, H - ( 1 / 3 ) )
	return (R,G,B)  

def getColorForUser(user):
	"""
	Algorithm borrowed from the chromatabs Firefox extension.
	"""
	def djb2hash(hashstring):
		hashvalue = 5381;
		for ascii_code in map(ord, hashstring):
			hashvalue = ((hashvalue << 5) + hashvalue) + ascii_code
		return hashvalue
	hue = djb2hash(user) % 360
	rgb = hsl(hue, SATURATION, LUMINANCE)
	rgb = tuple(map((lambda n: int(n * 0xFFFF)), rgb))
	return '#%04X%04X%04X' % rgb

def findMe():
	"""fineMe() -> str
	Finds the actual path of the ran program.
	"""
	if os.path.isfile(sys.argv[0]):
		return sys.argv[0]
	for path in os.environ['PATH'].split(os.pathsep):
		if os.path.isfile(os.path.join(path, sys.argv[0])):
			return os.path.join(path, sys.argv[0])

def resource(fn):
	paths = [
		os.curdir, # For development
		os.path.join(sys.prefix, 'share', 'subim'), # Assuming a single, global prefix
		# And now for some common prefix's
		'/'+os.path.join('usr', 'local', 'share', 'subim'),
		'/'+os.path.join('usr', 'share', 'subim'),
		# Relative to the script
		os.path.join(os.path.dirname(findMe()), os.pardir, 'share', 'subim'),
		# Now we're getting desparate
		os.path.join(os.pardir, 'share', 'subim'),
		]
	for path in paths:
		try:
			f = os.path.join(path, fn)
			if os.path.exists(f):
				return f
		except: pass
	else:
		print >> sys.stderr, "Couldn't find ", repr(fn)
		return fn #Can't actually find it

class MainWindow(object):
	def __listWidgets(self, root):
		"""
		Grabs the names of all the widgets and sets a property to that name.
		"""
		if not hasattr(root, 'get_children'): return
		for c in root.get_children():
			n = gtk.glade.get_widget_name(c)
			if n is None: 
				print "Not a Glade widget:", c
				continue # Wasn't an XML child
			setattr(self, n, c)
			self.__listWidgets(c)
	
	__initPanes = False
	def __init__(self, fn):
		self._xml = gtk.glade.XML(fn)
		self._xml.signal_autoconnect(self)
		self.wSubIM = self._xml.get_widget('wSubIM')
		self.__listWidgets(self.wSubIM) # Initialize all the props
		self.mStatusPopup = self._xml.get_widget('mStatusPopup')
		self.__listWidgets(self.mStatusPopup) # Initialize all the props
		
		self.wSubIM.set_icon_from_file(resource('subim.svg'))
		self.wSubIM.set_default_size(375, 500)
		
		self.tvUsers.append_column(gtk.TreeViewColumn('User', gtk.CellRendererText(), text=0))
		self.tvUsers.set_model(gtk.ListStore(str))
		self.umodel = self.tvUsers.get_model()
		self.umodel.set_sort_column_id(0, gtk.SORT_ASCENDING)
		self.tvUsers.sensitive = True
		self.userlist = []
		
		# System Tray icon
		if hasattr(gtk, 'status_icon_new_from_file'):
			self.siIcon = gtk.status_icon_new_from_file(resource('subim.svg'))
			self.siIcon.set_tooltip("SubIM - "+getHost())
			self.siIcon.set_visible(True)
			self.siIcon.connect("activate", self.statusActivate)
			self.siIcon.connect("popup-menu", self.statusPopup)
		else:
			self.siIcon = None
	
	def statusActivate(self, icon):
		if self.siIcon is None:
			self.QuitApp()
		elif self.wSubIM.get_property('visible'):
			self.wSubIM.hide()
		else:
			self.wSubIM.present()
	
	def ShowAbout(self, item=None):
		if not hasattr(gtk,'AboutDialog'):
			return
		REV = re.compile(r"""\$Revision:(.*)\$""")
		m = REV.match(__version__)
		if m:
			ver = "r"+m.group(1).strip()
		else:
			ver = __version__
		PROPS = {
			'name' : 'SubIM',
			'comments' : "A dirt simple IM program for your local subnet",
			'logo' : self.wSubIM.get_icon(),
			'version' : ver,
			'authors' : [__author__],
			'copyright' : "© 2007 James Bliss. Released under GNU GPL",
			'website' : 'http://www.astro73.com/',
		}
		ad = gtk.AboutDialog()
		for k,v in PROPS.items():
			try:
				ad.set_property(k,v)
			except Exception, err:
				print type(err), err
		ad.present()
		
	
	def QuitApp(self, item=None):
		self.wSubIM.hide()
		self.wSubIM.destroy()
		gtk.main_quit()
	
	def statusPopup(self, icon, button, time):
		self.mStatusPopup.popup(None, None, gtk.status_icon_position_menu, button, time, icon)
	
	def winDelete(self, widget, event):
		print "winDelete", widget, event
		self.wSubIM.hide()
		return True # Override
	
	def present(self):
		self.wSubIM.present()
		# Frankly, these two should be in the glade file
		self.tvMessage.grab_focus()
		self.bSend.grab_default()
		# And the fact that I have to do this after presenting is a little ridiculous
		if not self.__initPanes:
			self.vpInput.set_position(self.vpInput.get_position() - 50)
			self.hpUsers.set_position(self.hpUsers.get_position() - 75)
			self.__initPanes = True
	
	def getMessageText(self):
		buf = self.tvMessage.get_buffer()
		rv = buf.get_text(*buf.get_bounds())
		print "getMessageText:rv", type(rv), repr(rv)
		return unicode(rv, 'utf8', 'ignore')
	
	def sendMessage(self, *p, **kw):
		print "sendMessage", p, kw
		protocol.sendMessage(self.getMessageText())
		# Clear the input
		buf = self.tvMessage.get_buffer()
		buf.delete(*buf.get_bounds())
	
	def addUser(self, userName):
		print "addUser", userName
		if userName not in self.userlist:
			self.userlist.append(userName)
			self.addNotice(userName, "joined")
			i = self.umodel.append([userName])
			assert self.tvUsers.get_model() is self.umodel
	
	def rmUser(self, userName):
		print "rmUser", userName
		if userName in self.userlist:
			i = self.userlist.index(userName)
			del self.userlist[i]
			self.addNotice(userName, "left")
			for i in range(0, len(self.umodel)):
				if self.umodel[i][0] == userName:
					del self.umodel[i]
					return
	
	def sendMessageKey(self, widget, event):
		if event.type != gtk.gdk.KEY_PRESS: return
		#print "sendMessageKey", hex(event.state), hex(event.keyval), event.group, repr(event.string)
		if event.keyval == 0xFF0D or event.string == "\r":
			if event.state & 1: #Shift
				event.state &= ~1
				return False # Continue processing
			else: #Unshifted
				#self.bSend.emit("clicked")
				self.wSubIM.activate_default()
				return True # Stop processing
		elif event.keyval == 0xFF09: # Tab, for tab completion
			pass
	
	def scrollDown(self):
		"""
		Scroll to the bottom of the history.
		"""
		#FIXME: Sometimes, this causes the text to disappear
		va = self.swHistory.get_vadjustment()
		va.set_value(va.upper)
	
	def getTime(self):
		dt = datetime.datetime.now()
		dt = datetime.datetime(dt.year, dt.month, dt.day, dt.hour, dt.minute, dt.second, 0, dt.tzinfo)
		return u"[%s] " % unicode(dt)
	
	_first = True
	def addMessage(self, user, msg):
		buf = self.tvHistory.get_buffer()
		if not self._first:
			buf.insert(buf.get_bounds()[1], "\n")
		self._first = False
		ut = buf.create_tag(foreground=getColorForUser(user))
		buf.insert_with_tags(buf.get_bounds()[1], self.getTime()+user+":", ut)
		buf.insert(buf.get_bounds()[1], " "+msg.strip())
		self.scrollDown()
	
	def addNotice(self, user, msg):
		"""
		Like addMessage, but for things like quit/join.
		"""
		buf = self.tvHistory.get_buffer()
		if not self._first:
			buf.insert(buf.get_bounds()[1], "\n")
		self._first = False
		ut = buf.create_tag(weight=pango.WEIGHT_BOLD)
		buf.insert_with_tags(buf.get_bounds()[1], self.getTime()+user+" "+msg.strip(), ut)
		self.scrollDown()
	

if __name__ == '__main__':
	app = MainWindow(resource('subim.glade'))
	print repr(app)
	protocol = Protocol()
	
	def msgRecv(user, msg):
		global app
		app.addMessage(user, msg)
	def userJoined(user):
		global app
		app.addUser(user)
	def userParted(user):
		global app
		app.rmUser(user)
	
	protocol.joiners.append(userJoined)
	protocol.parters.append(userParted)
	protocol.msgers.append(msgRecv)
	
	protocol.startReading()
	
#	with protocol: Compatiblity with debian stable
	protocol.__enter__()
	try:
		protocol.listUsers()
		app.present()
		gtk.main()
	finally:
		protocol.__exit__()

